# Cuisine Code Docker Compose configuration
# Copyright (c) 2025 Aidan Pace

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: cuisine-code-api
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=cuisine
      - DB_PASSWORD=cuisine_password
      - DB_NAME=cuisine_code
    depends_on:
      - db
    networks:
      - cuisine_network
    volumes:
      - api_data:/app/data
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: cuisine-code-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - cuisine_network
      
  db:
    image: postgres:14-alpine
    container_name: cuisine-code-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=cuisine
      - POSTGRES_PASSWORD=cuisine_password
      - POSTGRES_DB=cuisine_code
    ports:
      - "5432:5432"
    networks:
      - cuisine_network
    volumes:
      - db_data:/var/lib/postgresql/data
      
  prometheus:
    image: prom/prometheus:latest
    container_name: cuisine-code-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - cuisine_network
      
  grafana:
    image: grafana/grafana:latest
    container_name: cuisine-code-grafana
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=cuisine_grafana
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - cuisine_network

networks:
  cuisine_network:
    driver: bridge

volumes:
  api_data:
  db_data:
  prometheus_data:
  grafana_data:
