openapi: 3.1.0
info:
  title: Cuisine Code User Profile API
  version: 1.0.0
  description: APIs for user profile management
paths:
  /api/users/profile:
    get:
      summary: Get user profile
      description: Get the current user's profile
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    put:
      summary: Update profile
      description: Update the current user's profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  /api/users/{id}:
    get:
      summary: Get user
      description: Get a specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicProfile'
  /api/users/kitchen:
    get:
      summary: Get kitchen
      description: Get the current user's kitchen configuration
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KitchenConfiguration'
    put:
      summary: Update kitchen
      description: Update the current user's kitchen configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KitchenUpdate'
      responses:
        '200':
          description: Kitchen updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KitchenConfiguration'
components:
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: User ID
        username:
          type: string
          description: Username
        display_name:
          type: string
          description: Display name
        email:
          type: string
          format: email
          description: Email address
        location:
          type: string
          description: User location
        bio:
          type: string
          description: User biography
        preferences:
          type: object
          description: User preferences
        created_at:
          type: string
          format: date-time
          description: Account creation time
    ProfileUpdate:
      type: object
      properties:
        display_name:
          type: string
          description: Display name
        location:
          type: string
          description: User location
        bio:
          type: string
          description: User biography
        preferences:
          type: object
          description: User preferences
    UserPublicProfile:
      type: object
      properties:
        id:
          type: string
          description: User ID
        username:
          type: string
          description: Username
        display_name:
          type: string
          description: Display name
        location:
          type: string
          description: User location
        bio:
          type: string
          description: User biography
    KitchenConfiguration:
      type: object
      properties:
        id:
          type: string
          description: Kitchen ID
        name:
          type: string
          description: Kitchen name
        location:
          type: string
          description: Kitchen location
        equipment:
          type: array
          items:
            $ref: '#/components/schemas/KitchenEquipment'
        layout:
          type: object
          description: Kitchen layout configuration
    KitchenEquipment:
      type: object
      properties:
        id:
          type: string
          description: Equipment ID
        type:
          type: string
          description: Equipment type
        name:
          type: string
          description: Equipment name
        quantity:
          type: integer
          description: Quantity
        properties:
          type: object
          description: Equipment properties
    KitchenUpdate:
      type: object
      properties:
        name:
          type: string
          description: Kitchen name
        location:
          type: string
          description: Kitchen location
        equipment:
          type: array
          items:
            $ref: '#/components/schemas/KitchenEquipment'
        layout:
          type: object
          description: Kitchen layout configuration
